### PR TITLE
Remove peer from active connections if send failed

### LINKED ISSUE #15: Update counters when a peer is disconnected
When a peer is disconnected, because his thread fail or have his socket shutdown we need to change the counters and infos in `active_connections` of the manager. Related to : https://github.com/massalabs/PeerNet/blob/main/src/peer.rs#L91

### PR DESCRIPTION
**Pull request by litchipi**
Closes #15 

Independant from #16 after all, so can be merged directly without it being pre-merged

### CODE REVIEW

File: src/peer.rs [hunk 1]
```diff
@@ -128,12 +128,20 @@ pub(crate) fn new_peer<T: HandshakeHandler>(
...
             match high_write_rx.try_recv() {
                 Ok(data) => {
                     println!("writer thread: high priority message received");
-                    write_endpoint.send(&data).unwrap();
+                    if write_endpoint.send(&data).is_err() {
+                        write_active_connections
+                            .write()
+                            .connections
+                            .remove(&write_peer_id)
+                            .expect("Unable to remove peer id");
```
Comment (AurelienFT) [inline src/peer.rs:143]: I think we should stop the peer thread as the channel to communicate with him doesn't work anymore. Same for the other lines added above.

File: src/peer.rs [hunk 2]
```diff
@@ -197,6 +212,10 @@ pub(crate) fn new_peer<T: HandshakeHandler>(
                 }
                 Err(err) => {
                     println!("Peer err {:?}", err);
+                    let mut active_connections = active_connections.write();
+                    active_connections.connections.remove(&peer_id).expect("Unable to remove peer id");
+                    let _ = write_thread_handle.join();
```
Comment (AurelienFT) [inline src/peer.rs:217]: Will the writer thread stop if the receive fail ? Because if the writer has nothing to write (that could happens especially if the connection isn't in the `active_connections` because it's the source of node connected for handlers) it will never try to write and then fail

File: src/peer.rs [hunk 3]
```diff
@@ -197,6 +212,10 @@ pub(crate) fn new_peer<T: HandshakeHandler>(
                 }
                 Err(err) => {
                     println!("Peer err {:?}", err);
+                    let mut active_connections = active_connections.write();
```
[the remark this answers is not in the document]
Comment (litchipi) [reply src/peer.rs:215]: Fixed

File: src/peer.rs (hunk 2 above)
Comment (litchipi) [reply src/peer.rs:213]: Hmmm ok, I don't see clearly how everything is wired yet. In which case does this have to fail and panic ?

File: src/peer.rs [hunk 4]
```diff
@@ -126,12 +126,21 @@ pub(crate) fn new_peer<T: HandshakeHandler>(
         // SPAWN WRITING THREAD
         //TODO: Bound
         let mut write_endpoint = endpoint.clone();
+        let write_active_connections = active_connections.clone();
+        let write_peer_id = peer_id.clone();
         // https://github.com/crossbeam-rs/crossbeam/issues/288
         let write_thread_handle = std::thread::spawn(move || loop {
```
Comment (modship) [inline src/peer.rs:132]: std:: thread::spawn is already import at line 4. If you want to prefix you can remove from the top

File: src/peer.rs [hunk 5]
```diff
@@ -173,10 +188,7 @@ pub(crate) fn new_peer<T: HandshakeHandler>(
                 Ok(data) => {
                     if data.is_empty() {
                         println!("Peer stop");
-                        {
-                            let mut active_connections = active_connections.write();
-                            active_connections.connections.remove(&peer_id);
-                        }
+                        active_connections.write().connections.remove(&peer_id).expect("Unable to remove peer id");
```
Comment (modship) [inline src/peer.rs:191]: expect() is intentional ?

File: src/peer.rs (hunk 4 above)
Comment (litchipi) [reply src/peer.rs:132]: I prefer to always prefix it, I think it's much more clear, I fixed the double import

File: src/peer.rs (hunk 5 above)
Comment (AurelienFT) [reply src/peer.rs:191]: Yes this should never happens but maybe a print could be enough as even if it happens it will not critically break the code.

**Comment by litchipi** [comment]
@modship Ready to merge if you think all is good

**Review by modship — APPROVED** [review]
